### ISSUE TITLE
Expiration date

### ISSUE THREAD

**Issue by TimothyGu** [LilyBin/LilyBin#40]
We should allow users to make a score expire once it is. Having the infrastructure in place to do this will also allow #25, since the Dropbox Savers API requires a URL to be present for the file to be stored.

**Comment by scottlinux** [comment]
A drop down to pick expiration like http://fpaste.org/ or https://paste.kde.org/ would be great.

**Comment by trevordixon** [comment]
Why is score expiry necessary to make Dropbox saving work?

**Comment by TimothyGu** [comment]
We need a URL for Dropbox to work, but I don't want to use up the resources of the server when it is already saved elsewhere :) So I thought maybe a way to automatically delete the key would be helpful.

**Comment by trevordixon** [comment]
It's already on S3 after `prepare_preview`. Can't we give Dropbox that URI?

**Comment by TimothyGu** [comment]
The score?

**Comment by TimothyGu** [comment]
Oops

**Comment by TimothyGu** [comment]
After the discussion in #47, I've decided to close this.
