### ISSUE TITLE
Set up a LilyBin organization

### ISSUE THREAD

**Issue by TimothyGu** [LilyBin/LilyBin#51]
Now we have three repos for LilyBin:

- This one
- Our fork of PDF.js [TimothyGu/pdf.js-lilybin](https://github.com/TimothyGu/pdf.js-lilybin)
- The Lambda function [TimothyGu/lilybin-slave](https://github.com/TimothyGu/lilybin-slave)

it is probably better if we put them all into a dedicated organization so that permissions and other things are shared.

**Comment by trevordixon** [comment]
Transferred to LilyBin organization.

**Comment by TimothyGu** [comment]
Moved the other two as well.
