### ISSUE TITLE
View compile log

### ISSUE THREAD

**Issue by rupert-git** [LilyBin/LilyBin#52]
Retroactively submitting a feature request that Timothy has already completed - thanks Timothy!

New button added to the right hand menu: "Show Lilypond Log". Tested and working in the Safari browser.

Currently, messages can be printed to the log by using 

```scheme
#(display "insert message here" (current-error-port))
```

TODO:

- [x] Make log window "sticky"
- [x] Pipe stdout to log

**Comment by TimothyGu** [comment]
TODO:

- [ ] Make log window "sticky"
- [ ] Pipe stdout to log

I have a fix for the second one but am currently unable to submit it to AWS Lambda. I'll see if I can upload the ZIP file to S3 first because uploading a 35 MB file directly to Lambda with the AWS CLI eats all my memory.

**Comment by TimothyGu** [comment]
stdout works now, so no need for `(current-error-port)`.

**Comment by TimothyGu** [comment]
Sticky log works now as well.
