### ISSUE TITLE
Add github authentication

### ISSUE THREAD

**Issue by shytikov** [LilyBin/LilyBin#58]
In #56 I've by mistake assumed that anonymous `gists` could be versioned. But apparently they are not.

I think it could be possible to add optional option to login using `github` OAuth2 protocol. The same way as for example, [gitter](http://gitter.im/) and [gitbook](http://gitbook.com/) work now. This will enable users to get more control over their scores stored on `github`:

* User will be always able to see list of his scores (since they will be linked to his account);
* Scores will have revisions;
* The user will be able to `git push` and `git pull` to and from `gist` and all the changes will be reflected in LilyBin.

**Comment by trevordixon** [comment]
I've assumed that the typical LilyPond user is more likely to use Dropbox than GitHub. Do you think that's true? We already do (or did and will again soon) Dropbox, which tracks revisions and provides easy syncing.

**Comment by shytikov** [comment]
Probably you're right once again :100: Regular user will prefer to have his / her scores saved to Dropbox. But once `OAuth` mechanism will be implemented new sources could be added very easily. 

For example sharing rendered score to FB, or Twitter...

**Comment by TimothyGu** [comment]
We are trying to move away from using a cloud instance for the website, and unfortunately OAuth basically requires a server backend to be secure. So, unless GitHub releases a Drop-ins API like [Dropbox's](https://www.dropbox.com/developers/dropins), this is not going to happen.

**Comment by shytikov** [comment]
By "cloud instance for the website" you mean database instance for storing OAuth tokens? Can [nedb](https://github.com/louischatriot/nedb) become a solution?

@TimothyGu @trevordixon what do you think about having [Gitter](http://gitter.im/) room for discussions?

I'm really interested in helping your project (I'm very enthusiastic about `LilyPond`), but I don't want to open a issue every time when I have stupid question :)

**Comment by TimothyGu** [comment]
> By "cloud instance for the website" you mean database instance for storing OAuth tokens?

I guess you can say that. nedb runs on a server, and we kind of want LilyBin to be serverless.

**Comment by shytikov** [comment]
Aha! So you're talking just about serving static files?

**Comment by trevordixon** [comment]
Yep, the front end will be all static files. Right now the Node.js server proxies requests to AWS Lambda and stores scores. The API Gateway will handle the first function, and Gists will do the second.

**Comment by shytikov** [comment]
If I may ask question (I'm not a Lambda expert) how did you managed to make it respond with `LilyPond` processing results? They have some kind of preset that captures input and throws it to `LilyPond` executable and than captures results, that we see? 

It's could be done with any linux application there on Lambda?

**Comment by trevordixon** [comment]
You can upload anything you want (up to 50 megabytes, zipped), including Linux executables. Then you can execute it from Node.js. See https://github.com/LilyBin/lambda-function/blob/master/index.js#L32-L35.
