### ISSUE TITLE
Consider SVG as default output format.

### ISSUE THREAD

**Issue by shytikov** [LilyBin/LilyBin#60]
One idea. 

For me reloading of scores after save takes some time, I think it's not only processing on server-side, but also PDF rendering on client side... I found for me `SVG` representation of score actually does better job... It's natively supported, so opens noticeably quicker, and it looks a way nicer, lines are more crisp.

I must admit `lilypond` does not "gzip" output, but since it could be done on server-side it's also possible to optimize bandwidth usage, which will great for both client and server.

Here calculations based on my favorite score:

* `PDF` — 176,845 bytes
* `PNG` — 95,397 bytes
* `SVG` ­— 302,864 bytes

-------

* `PDF / gz` — 91,855 bytes
* `PNG / gz` — 91,572 bytes
* `SVG / gz` — **28,050 bytes**

`PNG` output was created with `-fpng` switch, `SVG` was created with `-dbackend=svg` switch.

I think switching to gzipped `SVG` will lead to lower bandwidth usage on server and client, easier for CPU on client side, much more crisp and nice for end users' eyes, thus improving performance and usability for end users.

**Comment by trevordixon** [comment]
We looked into this. LilyPond takes longer (*way* longer in many cases) to render SVG than PDF. See https://github.com/LilyBin/LilyBin/issues/48.
