### ISSUE TITLE
Use new Amazon API Gateway to invoke Lambda functions

### ISSUE THREAD

**Issue by trevordixon** [LilyBin/LilyBin#61]
I set up an [Amazaon API Gateway](https://aws.amazon.com/blogs/aws/amazon-api-gateway-build-and-run-scalable-application-backends/), so now we can do this to render scores:

```
jQuery.post('https://7icpm9qr6a.execute-api.us-west-2.amazonaws.com/prod/stable', JSON.stringify({
  body: "% LilyBin\n\\score{\n\t{\n\t\tc' c' d' e' f' f' f'2\n\t}\n\n\t\\layout{}\n\t\\midi{}\n}\n",
  key: "abcdefg"
}))
```

We almost don't need the EC2 instance after this! Then we can use S3 or GitHub pages to host the front end.

**Comment by TimothyGu** [comment]
This doesn't look safe from DDoS. What a person cooks up thousands of these requests in a few minutes? The cost that would incur is difficult to control. Does AWS offer any kind of protection or throttling against that?

**Comment by scottlinux** [comment]
I'm at the AWS Summit in NY and just saw a presentation on this. It is awesome. You can throttle requests with some limited settings. I assume this service will continue to gain more features.

**Comment by trevordixon** [comment]
<img width="607" alt="screen shot 2015-07-10 at 7 07 18 am" src="https://cloud.githubusercontent.com/assets/1253245/8620132/5f114ac4-26d2-11e5-9f35-9174faa6ee81.png">

Those are the controls available now. Like Scott, I expect they'll add more features.

**Comment by TimothyGu** [comment]
Okay, I guess 200/100 is pretty good for now.

**Comment by TimothyGu** [comment]
I finally found time to work on this again. Hopefully I'll fix this over this weekend.

**Comment by TimothyGu** [comment]
Just converted prepare_preview to API gateway. The only thing left now is Gist integration.

**Comment by PaulMorris** [comment]
Looks like this issue could be closed, after this commit? https://github.com/LilyBin/LilyBin/commit/e761102cd4f5b07d7fcfe93d650b37e6730c4f39

**Comment by TimothyGu** [comment]
Yep :)
