### ISSUE TITLE
Can not render longer scores

### ISSUE THREAD

**Issue by liuyang1204** [LilyBin/LilyBin#71]
When I try to render longer scores (more than one page), the pdf reader gets stuck on loading.

Seems to be 'Access-Control-Allow-Origin' problem:
```
XMLHttpRequest cannot load https://s3-us-west-2.amazonaws.com/lilybin-scores/swaj09.pdf?t=1452624473212. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.lilybin.com' is therefore not allowed access. The response had HTTP status code 403.
```

However, I could open the pdf file URL in a new tab.

**Comment by trevordixon** [comment]
Confirmed. http://lilybin.com/zacig0/1 It's an OPTIONS request that's failing.

**Comment by trevordixon** [comment]
This fails:

    curl 'https://s3-us-west-2.amazonaws.com/lilybin-scores/x02kxz.pdf' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: http://lilybin.com' -H 'Access-Control-Request-Headers: range'

But this doesn't:

    curl 'https://s3-us-west-2.amazonaws.com/lilybin-scores/x02kxz.pdf' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: http://lilybin.com'

Has something to do with the Access-Control-Request-Headers: range header.

**Comment by trevordixon** [comment]
Adding `<AllowedHeader>Range</AllowedHeader>` to CORS configuration fixed it.

**Comment by trevordixon** [comment]
Thanks for the report @liuyang1204!
