### ISSUE TITLE
Signature expired

### ISSUE THREAD

**Issue by larsenwork** [LilyBin/LilyBin#72]
![screen shot 2016-01-16 at 16 50 09](https://cloud.githubusercontent.com/assets/3859425/12373185/50d3c6fa-bc71-11e5-997b-ca09f37be852.png)

**Comment by scottlinux** [comment]
Signature expired: 20160117T015330Z is now earlier than 20160117T015332Z (20160117T015832Z - 5 min.)

Some kind of clock is not in sync. lilybin.com is currently entirely in AWS using lambda so this is pretty odd.

**Comment by TimothyGu** [comment]
> lilybin.com is currently entirely in AWS using lambda so this is pretty odd.

The website front end is still hosted on EC2. I'll investigate.

**Comment by TimothyGu** [comment]
Fixed. Turns out the clock on the EC2 server is about 5 minutes slower than real time. Fixed by installing an NTP client.
